export enum ApiErrorStatus {
    PHONE_EXISTED = "PHONE_EXISTED",
    INVALID_OTP = "INVALID_OTP",
    EXPIRED_OTP = "EXPIRED_OTP",
    EXPIRED_TOKEN = "EXPIRED_TOKEN",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
    OUT_OF_STOCK = "OUT_OF_STOCK",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    SERVER_ERROR = "SERVER_ERROR",
    
}