export enum OrderAction {
  CANCEL_ORDER = "CANCEL_ORDER",
  CREATE_ORDER = "CREATE_ORDER",
  CONFIRM_ORDER = "CONFIRM_ORDER",
  SHIPPING_ORDER = "SHIPPING_ORDER",
  CONFIRM_PAYMENT ="CONFIRM_PAYMENT",
  COMPLETE_ORDER = "COMPLETE_ORDER",
  RETURN_ORDER = "RETURN_ORDER",
  REFUND_ORDER = "REFUND_ORDER"
}